version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor:
        update-types:
          - minor
      patch:
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      minor:
        update-types:
          - minor
      patch:
        update-types:
          - patch
